### PR TITLE
refactor(wallet): add wallet to testnet label

### LINKED ISSUE #883: Add "wallet" to testnet label
Bossman politely requests we add "wallet" to "testnet" label:

Screenshot 2023-10-13 at 9 57 45 AM

A la:

Screenshot 2023-10-13 at 9 57 36 AM

### PR DESCRIPTION
**Pull request by HeetVekariya**
### Context

- fixes #883 
- Add ```wallet``` to the ```testnet``` label

### Changes
- Updated label: ```testnet wallet```
- File changed: **```Menu.tsx```** (packages/wallet/frontend/src/components/Menu.tsx)

### Total changes: 1

### CODE REVIEW

**Review by Tymmmy — APPROVED** [review]

**Comment by Tymmmy** [comment]
Thank you @HeetVekariya  approved and squashed-merged into master.
Please follow announcements for the swag details here: https://community.interledger.org/devcer/hacktoberfest-with-interledger-join-the-open-payments-movement-3bkd

**Comment by HeetVekariya** [comment]
- @Tymmmy Thank you for merging.
- I have joined the slack, but i don't how to claim the swag. Can you help me with that

**Comment by Tymmmy** [comment]
@HeetVekariya all info will be shown there, when hacktober is over.

**Comment by devcer** [comment]
@HeetVekariya Thank you for Contributing to Interledger during Hacktoberfest. If you have any accepted PRs, You can claim your Swag [here](https://community.interledger.org/devcer/hacktoberfest-swag-redemption-claim-your-cool-gear-2152). Last date to fill up the form is December 10th, 2023.

**Comment by HeetVekariya** [comment]
> @HeetVekariya Thank you for Contributing to Interledger during Hacktoberfest. If you have any accepted PRs, You can claim your Swag [here](https://community.interledger.org/devcer/hacktoberfest-swag-redemption-claim-your-cool-gear-2152). Last date to fill up the form is December 10th, 2023.

- Thank you for the swag, i have filled the form.

**Pull request merged**
