### PR TITLE
fix: updated the headlessui/react package and refactored its usage

### LINKED ISSUE #1616: [BUG] Delete headless ui deprecated code after recent update
### Steps to reproduce

We need to remove <Transition> deprecated code.
<Transition.Child> <Transition.Root>  etc.

### Expected result

Remove deprecated code from all files using it

### Actual result

Code does not contain deprecated tags

### Screenshots or videos
image

### Additional context

_No response_

### Operating system

macOS

### Operating system version

_No response_

### Browsers

Chrome

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by chavdarohit**
### Context

- fixes #1616

### Changes

- Refactored the `Dialog` and `Transition` components from the `headlessui/react` package to ensure compatibility with the latest version.
- Removed deprecated code related to these components after the recent update.

### CODE REVIEW

**Comment by Tymmmy** [comment]
@chavdarohit please add a comment to the story, so I can assign it to you

**Comment by chavdarohit** [comment]
I hope you’re doing well! Just wanted to check in on my PR submitted yesterday. I’d appreciate any feedback when you have a moment.

**Comment by Tymmmy** [comment]
@chavdarohit looking good, doing a deployment right now, so I just need a few more days until I aprove this and merge it to master. Will be done this week probably. Sorry for making you waot a bit. But everything looks ok.

**Comment by chavdarohit** [comment]
@Tymmmy  Thank you for the update! No worries at all—I appreciate your efforts. I look forward to the merge when you’re ready. :)

**Review by Tymmmy — APPROVED** [review]

**Comment by Tymmmy** [comment]
@chavdarohit can you take a look at the build errors? There might be an extra dialog maybe added since then and that is why you need to remove from an extra file some code.

**Comment by chavdarohit** [comment]
yaa i got the problem it is because the conflict let me fix it

**Comment by chavdarohit** [comment]
i just updated the PR can you try again

**Comment by Tymmmy** [comment]
Looks like prettier checks, maybe try pnpm format? @chavdarohit

**Review by Tymmmy — APPROVED** [review]

**Comment by Tymmmy** [comment]
@chavdarohit well done, merged to master. Thank you for the contribution.

**Comment by chavdarohit** [comment]
Thanks for merging 🏁 also can you mark the issue close and add the label of the hacktoberfest-accepted it will be glad

**Comment by chavdarohit** [comment]
@Tymmmy could you please add the label for the hacktoberfest-accepted then only my contribution will count for that

**Comment by chavdarohit** [comment]
@Tymmmy i can understand but already what happened if the hacktoberfest community is not accepting the pr within 7 days so timer will go and it will be not accepted but if there is hacktoberfest-accepted label in this PR after the time will complete it will automatically accept so i am requesting to just add it

**Pull request merged**
